AplikasiPDAMTanjungUban/Controllers/LaporanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplikasiPDAMTanjungUban.Data;
using AplikasiPDAMTanjungUban.Models;
using Microsoft.AspNetCore.Mvc;

namespace AplikasiPDAMTanjungUban.Controllers
{
    public class LaporanController : Controller
    {
        private readonly ApplicationDbContext _db;

        public LaporanController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region API CALLS

        public JsonResult GetAll()
        {
            List<Pembayaran> listPembayaran = _db.Pembayarans.OrderBy(x => x.Id).ToList();

            return Json(new { data = listPembayaran });
        }

        public JsonResult TampilData(string tglAwal, string tglAkhir)
        {
            List<Pembayaran> listPembayaran = _db.Pembayarans.Where(x=> x.Tanggal>=Convert.ToDateTime(tglAwal) && x.Tanggal<=Convert.ToDateTime(tglAkhir)).ToList();

            return Json(new { data = listPembayaran });
        }

        #endregion
    }
}

AplikasiPDAMTanjungUban/Controllers/PembayaranController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplikasiPDAMTanjungUban.Data;
using AplikasiPDAMTanjungUban.Models;
using AplikasiPDAMTanjungUban.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AplikasiPDAMTanjungUban.Controllers
{
    public class PembayaranController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PembayaranController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            PembayaranVM vm = new PembayaranVM();

            vm = new PembayaranVM()
            {
                Pembayaran = new Pembayaran()
                {
                    Tanggal = DateTime.Now,
                    BiayaAdmin = 1000.0
                },

                ListPelanggan = _db.Pelanggans.Select(i => new SelectListItem
                {
                    Text = i.Nama,
                    Value = i.Id.ToString()
                })
            };

            return View(vm);
        }

        #region API CALLS

        public JsonResult GetDataPelanggan(int Id)
        {
            var listPelanggan = _db.Pelanggans.Where(x=> x.Id == Id).FirstOrDefault();

            string golongan = listPelanggan.Kategori;

            var tarif = _db.Tarifs.Where(x => x.Kategori == golongan).FirstOrDefault();

            PelangganVM vm = new PelangganVM()
            {
                Pelanggan = new Pelanggan()
                {
                    Id = listPelanggan.Id,
                    Alamat = listPelanggan.Alamat,
                    IdPelanggan = listPelanggan.IdPelanggan,
                    Kategori = listPelanggan.Kategori,
                    Kontak =listPelanggan.Kontak,
                    Nama = listPelanggan.Nama
                },

                Tarif = new Tarif()
                {
                    Biaya010 = tarif.Biaya010,
                    Biaya1120=tarif.Biaya1120,
                    Biaya2130=tarif.Biaya2130,
                    Biaya30=tarif.Biaya30,
                    Id=tarif.Id,
                    Kategori=tarif.Kategori
                }
            };

            return Json(new { data = vm });
        }

        [HttpPost]
        public IActionResult SimpanData(Pembayaran kr)
        {
            if (kr.Id == 0)
            {
                var plgn = _db.Pelanggans.Where(x => x.Id == Convert.ToInt16(kr.NamaPelanggan)).FirstOrDefault();

                if (plgn != null)
                {
                    kr.NamaPelanggan = plgn.Nama;
                    _db.Pembayarans.Add(kr);
                    _db.SaveChanges();
                    TempData["Success"] = "Data Pembayaran Berhasil di Tambahkan";
                }

                //TempData["Error"] = "Terjadi Kesalahan !!";
            }

            if (kr == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "Home");
        }

        #endregion
    }
}

AplikasiPDAMTanjungUban/Controllers/TarifController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AplikasiPDAMTanjungUban.Data;
using AplikasiPDAMTanjungUban.Models;
using AplikasiPDAMTanjungUban.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace AplikasiPDAMTanjungUban.Controllers
{
    public class TarifController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TarifController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            Tarif vm = new Tarif();

            return View(vm);
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {

            Tarif kr = new Tarif();

            if (id == null)
            {
                return View(kr);
            }

            var data = _db.Tarifs.Where(x => x.Id == id).FirstOrDefault();

            kr.Id = data.Id;
            kr.Kategori = data.Kategori;
            kr.Biaya010 = data.Biaya010;
            kr.Biaya1120 = data.Biaya1120;
            kr.Biaya2130 = data.Biaya2130;
            kr.Biaya30 = data.Biaya30;

            if (kr == null)
            {
                return NotFound();
            }

            return View(kr);

        }

        [HttpDelete]
        public IActionResult Delete(int Id)
        {
            var objFromDb = _db.Pelanggans.Find(Id);

            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }

            _db.Pelanggans.Remove(objFromDb);
            _db.SaveChanges();
            return Json(new { success = true, message = "Delete Successful" });
        }

        [HttpPost]
        public IActionResult Upsert(Tarif kr)
        {
            if (kr.Id == 0)
            {
                _db.Tarifs.Add(kr);
                _db.SaveChanges();

                TempData["success"] = "Tarif berhasil di tambahkan";
            }
            else
            {
                _db.Tarifs.Update(kr);
                TempData["success"] = "Tarif berhasil di ubah";

            }

            _db.SaveChanges();

            return RedirectToAction("Index");

        }

        #region API CALLS

        public JsonResult GetAll()
        {
            List<Tarif> listTarif = _db.Tarifs.ToList();

            return Json(new { data = listTarif });
        }
        #endregion
    }
}

AplikasiPDAMTanjungUban/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no" />
    <title>@ViewData["Title"] - AplikasiPDAMTanjungUban</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplikasiPDAMTanjungUban.styles.css" asp-append-version="true" />

    @*baru tambahin*@
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">

    <title>Chain App Dev - App Landing Page HTML5 Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!--

    TemplateMo 570 Chain App Dev

    https://templatemo.com/tm-570-chain-app-dev

    -->
    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/templatemo-chain-app-dev.css">
    <link rel="stylesheet" href="~/css/animated.css">
    <link rel="stylesheet" href="~/css/owl.css">

    @*datatable & toastr*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

</head>
<body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- ***** Header Area Start ***** -->
    <header id="navBar" class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a class="logo">
                            <img src="~/images/logo.png" alt="Chain App Dev">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">

                            <li class="scroll-to-section"><a asp-controller="Home" asp-action="Index" class="">Home</a></li>
                            <li class="scroll-to-section"><a href="#newsletter">About</a></li>

                            @if (StaticDetails.Role.Equals("Superadmin"))
                            {
                                <li class="scroll-to-section"><a asp-action="Index" asp-controller="Pelanggan">Pelanggan</a></li>
                                <li class="scroll-to-section"><a asp-action="Index" asp-controller="Tarif">Tarif</a></li>
                                <li class="scroll-to-section"><a asp-action="Index" asp-controller="Pembayaran">Pembayaran</a></li>
                                <li style="font-weight:bold" class="scroll-to-section"><a asp-action="Index" asp-controller="Laporan">Laporan</a></li>
                                <li><div class="gradient-button"><a asp-action="Logout" asp-controller="Home"><i class="fa fa-sign-in-alt"></i> Log out</a></div></li>
                            }
                            else if (StaticDetails.Role.Equals("Admin"))
                            {
                                <li class="scroll-to-section"><a asp-action="Index" asp-controller="Pelanggan">Pelanggan</a></li>
                                <li class="scroll-to-section"><a asp-action="Index" asp-controller="Pembayaran">Pembayaran</a></li>
                                <li style="font-weight:bold" class="scroll-to-section"><a asp-action="Index" asp-controller="Laporan">Laporan</a></li>
                                <li><div class="gradient-button"><a asp-action="Logout" asp-controller="Home" id="modal_trigger"><i class="fa fa-sign-in-alt"></i> Log out</a></div></li>
                            }
                            else
                            {
                                <li><div class="gradient-button"><a id="modal_trigger" href="#modal"><i class="fa fa-sign-in-alt"></i> Log In Now</a></div></li>
                            }
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <div id="modal" class="popupContainer" style="display:none;">
        <div class="popupHeader">
            <span class="header_title">Login</span>
            <span class="modal_close"><i class="fa fa-times"></i></span>
        </div>

        <section class="popupBody">
            <!-- Social Login -->
            <div class="social_login">
                <div class="action_btns">
                    @*<div class="one"><a href="#" id="login_form" class="btn">Login</a></div>*@
                    @*<div class="one_half last"><a href="#" id="register_form" class="btn">Sign up</a></div>*@
                </div>

                <div class="action_btns">
                    <form>
                        <div style="display:flex;flex-direction:column;margin-bottom:10px">

                            <div>
                                <label>Email / Username</label>
                                <input id="txtUsername" class="col-lg-12" type="text" />
                                <span class="text-danger"></span>
                                <br />
                            </div>
                            <div style="margin-top:10px;">
                                <label>Password</label>
                                <input id="txtPassword" class="col-lg-12" type="password" />
                                <span class="text-danger"></span>
                                <br />
                            </div>
                        </div>

                        <div class="action_btns">
                            @*<div class="one_half_last"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>*@
                            <div class="one">

                                <input onclick="Login()" value="Login" class="btn btn_red" />

                            </div>
                        </div>
                    </form>
                </div>

            </div>

            <!-- Username & Password Login form -->
            <div class="user_login">
                <form>
                    <label>Email / Username</label>
                    <input type="text" />
                    <br />

                    <label>Password</label>
                    <input type="password" />
                    <br />

                    @*<div class="checkbox">
                            <input id="remember" type="checkbox" />
                            <label for="remember">Remember me on this computer</label>
                        </div>*@

                    <div class="action_btns">
                        <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                        <div class="one_half last"><a href="#" class="btn btn_red">Login</a></div>
                    </div>
                </form>

                <a href="#" class="forgot_password">Forgot password?</a>

            </div>

            <!-- Register Form -->
            @*<div class="user_register">
                    <form>
                        <label>Full Name</label>
                        <input type="text" />
                        <br />

                        <label>Email Address</label>
                        <input type="email" />
                        <br />

                        <label>Password</label>
                        <input type="password" />
                        <br />

                        <div class="checkbox">
                            <input id="send_updates" type="checkbox" />
                            <label for="send_updates">Send me occasional email updates</label>
                        </div>

                        <div class="action_btns">
                            <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                            <div class="one_half last"><a href="#" class="btn btn_red">Register</a></div>
                        </div>
                    </form>
                </div>*@
        </section>
    </div>

    <div class="container">
        <main role="main" class="pb-3 mt-10">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer id="newsletter">
        <div id="divFooter" class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <div class="section-heading">
                        <h4>PDAM TIRTA KEPRI CABANG TANJUNG UBAN</h4>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="footer-widget">
                        <h4>Contact Us</h4>
                        <p>Jl. Bhakti Praja, Tj. Uban Kota, Kec. Bintan Utara, Kabupaten Bintan, Kepulauan Riau 29152</p>
                        <p><a href="#">0771-020-0340</a></p>
                        <p><a href="#">pdamtanjunguban@kepri.com</a></p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="footer-widget">
                        <h4>About Us</h4>
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Services</a></li>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Testimonials</a></li>
                            <li><a href="#">Pricing</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Testimonials</a></li>
                            <li><a href="#">Pricing</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="footer-widget">
                        <h4>About Our Company</h4>
                        <div class="logo">
                            <img src="~/logos/pdamlogo.png" alt="">
                        </div>
                        <p>Budaya Bersih dan Melayani</p>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="copyright-text">
                        <p>
                            Copyright © 2022 Chain App Dev Company. All Rights Reserved.
                            <br>Design: <a href="https://templatemo.com/" target="_blank" title="css templates">TemplateMo</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Scripts -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/owl-carousel.js"></script>
    <script src="~/js/animation.js"></script>
    <script src="~/js/imagesloaded.js"></script>
    <script src="~/js/popup.js"></script>
    <script src="~/js/custom.js"></script>

    <script src="~/js/Login.js"></script>

    @*datatable & toastr*@
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AplikasiPDAMTanjungUban/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}
else if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.error('@TempData["Error"]');
    </script>
}